---
# Variable configuration.
- name: Include OS-specific variables
  ansible.builtin.include_vars: '{{ platform_vars }}'
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: platform_vars

- name: Set upgrade OS
  ansible.builtin.set_fact:
    upgrade_os: "{{ __upgrade_os }}"
  when: upgrade_os is undefined

- name: Set the zsh plugins.
  ansible.builtin.set_fact:
    zsh_plugins: "{{ __zsh_plugins }}"
  when: zsh_plugins | length == 0

# Install pimp my shell
- name: Configure system
  ansible.builtin.include_tasks: '{{ platform }}'
  with_first_found:
    - 'setup-{{ ansible_os_family }}.yml'
    - 'setup-{{ ansible_distribution }}.yml'
    - 'not-supported.yml'
  loop_control:
    loop_var: platform

- name: Install extra CLI applications
  include_tasks: extra-cil.yml
