---
- name: Get facts
  ansible.builtin.setup:
    
# Variable configuration.
- name: Include OS-specific variables
  ansible.builtin.include_vars: '{{ platform_vars }}'
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: platform_vars

- name: Set upgrade OS
  ansible.builtin.set_fact:
    upgrade_os: "{{ __upgrade_os }}"
  when: upgrade_os is undefined

- name: Set aliases
  ansible.builtin.set_fact:
    aliases: "{{ __aliases }}"
  when: aliases is undefined

- name: Set apps links
  ansible.builtin.set_fact:
    apps_links: "{{ __apps_links | default([]) }}"
  when: apps_links is undefined

- name: Set the zsh plugins.
  ansible.builtin.set_fact:
    zsh_plugins: "{{ __zsh_plugins }}"
  when: zsh_plugins | length == 0

# Install pimp my shell
- name: Configure system
  ansible.builtin.include_tasks: '{{ platform }}'
  with_first_found:
    - 'setup-{{ ansible_os_family }}.yml'
    - 'setup-{{ ansible_distribution }}.yml'
    - 'not-supported.yml'
  loop_control:
    loop_var: platform

- name: Create .zshrc file
  ansible.builtin.template:
    src: .zshrc.j2
    dest: "{{ ansible_env['HOME'] }}/.zshrc"
    mode: 0644
    owner: "{{ ansible_env['USER'] | default(omit) }}"
    group: "{{ ansible_env['USER'] | default(omit) }}"
    force: false
  changed_when:
    - "'molecule-idempotence-notest' not in ansible_skip_tags"
    # - "'molecule-notest' not in ansible_skip_tags"

- name: Install extra CLI applications (git)
  include_tasks: extra-cli-git.yml
  when:
    - apps_source == "git"

- name: Configure prompt renderer
  ansible.builtin.include_tasks: 'prompt-{{ prompt_renderer }}.yml'

- name: Configure fzf
  ansible.builtin.blockinfile:
    path: "{{ ansible_env['HOME'] }}/.zshrc"
    content: "{{ fzf_env_config }}"
    state: present
  when: enable_fzf | default(true)

- name: Create aliases
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env['HOME'] }}/.zshrc"
    line: "alias {{ item.alias }}='{{ item.command }}'"  # exa/bat alias for zsh shell
    state: present
  when: item.state
  loop: "{{ aliases }}"

- name: Change user shell
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    shell: "{{ zsh_shell_path }}"
  changed_when:
    - "'molecule-idempotence-notest' not in ansible_skip_tags"
  tags: molecule-notest
  become: true
