---
- name: Check if Oh-My-Zsh is already installed
  ansible.builtin.stat:
    path: /{{ ansible_env['HOME'] }}/.oh-my-zsh
  ignore_errors: true
  register: omz_exist

- name: Download Oh-My-Zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install.sh
    mode: 0755

- name: Install Oh-My-Zsh
  ansible.builtin.command:
    cmd: "/tmp/install.sh --unattended"
  register: omz_installed
  changed_when: 
    - omz_installed.rc == 0
    - "'molecule-idempotence-notest' not in ansible_skip_tags"
  when: omz_exist.stat is defined and omz_exist.stat.exists

# TODO make more generic for other plugins
- name: Download Oh-My-Zsh Plugins
  ansible.builtin.git:
    name: "https://github.com/zsh-users/{{ item }}"
    dest: "{{ zsh_custom_path }}/plugins/{{ item }}"
    clone: true
    version: master
  when: enable_zsh_plugins | default(true)
  loop: "{{ zsh_plugins }}"

- name: Enable Oh-My-Zsh Plugins
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env['HOME'] }}/.zshrc"
    regexp: "^plugins=(.*)"
    line: "plugins=({{ zsh_plugins | join(' ') + ' fzf' if enable_fzf | default(true) else '' }})"
    state: present
  when: enable_zsh_plugins | default(true)

- name: Install Powerline10k
  ansible.builtin.git:
    name: "https://github.com/romkatv/powerlevel10k"
    dest: "{{ zsh_custom_path }}/themes/powerlevel10k"
    clone: true
    version: master
  when: enable_zsh_powerline10k | default(true)

- name: Enable Powerline10k
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env['HOME'] }}/.zshrc"
    regexp: "^ZSH_THEME=.*"
    line: "ZSH_THEME=\"powerlevel10k/powerlevel10k\""
    state: present
  when: enable_zsh_powerline10k | default(true)
