---
# - name: Get collection
#   ansible.builtin.command: ansible-galaxy collection install -r ./files/darwin-requirements.yml
#   changed_when: false
#   # register: result
#   # until: result.rc == 0

# - name: install brew
#   ansible.builtin.include_role:
#     - geerlingguy.mac.homebrew_cask

- name: Set package source (OS {{ ansible_distribution }})
  ansible.builtin.set_fact:
    apps_source: "{{ __apps_source }}"
  when: apps_source is undefined

- name: Install CLI applications
  community.general.homebrew:
    name: "{{ common_packages }}"
    state: present
    upgrade_all: true

- name: Install Graphical applications
  community.general.homebrew_cask:
    name: "{{ graphical_apps }}"
    state: present

- name: Install extra CLI applications
  block:
    - name: Set extra packages to install
      ansible.builtin.set_fact:
        extra_packages: "{{ 'fzf' if enable_fzf | default(true) else '' + 'exa' if enable_exa | default(true) else '' + 'bat' if enable_bat | default(true) else '' + 'fd' if enable_fd | default(true) else '' }}"

    - name: Install fzf
      community.general.homebrew:
        name: "{{ extra_packages }}"
        state: present
