---
- name: Set UTF-8 locale
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: wheel
  loop:
    - { src: etc/login.conf, dest: /etc/login.conf }
    - { src: usr/share/local/, dest: /usr/share/local/ }
  tags:
    - pfsense

- name: Create capability database
  ansible.builtin.command:
    cmd: cap_mkdb /etc/login.conf
  changed_when: false
  # register: result
  # until: result.rc == 0
  tags:
    - pfsense
