---
- name: Set package source (OS {{ ansible_distribution }})
  ansible.builtin.set_fact:
    apps_source: "{{ __apps_source }}"
  when: apps_source is undefined

- name: Add exa repository
  ansible.builtin.apt_repository:
    repo: "{{ exa_repo }}"
    state: present
    filename: "spvkgn-ubuntu-exa.list"
  when: apps_source == "package"
  become: true
  
- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
    upgrade: "{{ upgrade_os | default(false) }}"
    cache_valid_time: 86400
  become: true

- name: Install Pre-requirements CLI applications
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
  become: true

- name: Install extra CLI applications (package)
  ansible.builtin.apt:
    name: "{{ extra_packages }}"
    state: present
  when: apps_source == "package"
  become: true

- name: Add links to apps installed via package
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: link
  loop: "{{ apps_links }}"
  when:
    - apps_source == "package"
    - item.state
  become: true
