---
- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
    upgrade: "{{ upgrade_os | default(false) }}"
    cache_valid_time: 86400
  become: true

- name: Install Pre-requirements CLI applications
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
  become: true
