---
- name: Set package source (OS {{ ansible_distribution }})
  ansible.builtin.set_fact:
    apps_source: "{{ __apps_source }}"

- block:
    - name: Upgrade OS (Redhat 8.x)
      ansible.builtin.dnf:
        update_cache: true
        name: "*"
        state: "{{ 'latest' if upgrade_os | default(false) else 'present' }}"
      when:
        - upgrade_os | default(false)

    - name: Install Pre-requirements CLI applications (Redhat 8.x)
      ansible.builtin.dnf:
        name: "{{ common_packages }}"
        state: present
      register: common_installed
  when: ansible_distribution_major_version | int >= 8
  become: true

- block:
    - name: Update python alternative
      community.general.alternatives:
        link: /usr/bin/python
        name: python
        path: /usr/bin/python3
      changed_when:
        - "'molecule-idempotence-notest' not in ansible_skip_tags"

    - name: Upgrade OS (Redhat 7.x)
      ansible.builtin.yum:
        update_cache: true
        name: "*"
        state: "{{ 'latest' if upgrade_os | default(false) else 'present' }}"
      changed_when:
        - "'molecule-idempotence-notest' not in ansible_skip_tags"
      when:
        - upgrade_os | default(false)

    - name: Install Pre-requirements CLI applications (Redhat 7.x)
      ansible.builtin.yum:
        name: "{{ common_packages + common_packages_7 }}"
        state: present
      changed_when:
        - "'molecule-idempotence-notest' not in ansible_skip_tags"
      register: common_installed
  when: ansible_distribution_major_version | int == 7
  become: true
