---
- name: Converge
  hosts: all
  # gather_facts: false
  # become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    # Ubuntu-specific tasks.
    - name: Ensure dirmngr is installed (gnupg dependency).
      ansible.builtin.apt:
        name: dirmngr
        state: present
      when: ansible_os_family == 'Debian'
      ignore_errors: true

  tasks:
    - name: "Include pincher95.pimpmyshell"
      ansible.builtin.include_role:
        name: "pincher95.pimpmyshell"
